# -*- coding: utf-8 -*-
"""
/***************************************************************************
 NowcastTool
                                 A QGIS plugin
 Tiletool for weather forecast tiles by Japan Meteorological Agency
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-06-12
        copyright            : (C) 2021 by Kanahiro Iguchi
        email                : kanahiro.iguchi@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load NowcastTool class from file NowcastTool.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .nowcast_tool import NowcastTool
    return NowcastTool(iface)
